import type { HabitDomain, HabitFrequency, HabitTarget } from "@/types/habit";

export interface MasterHabitDefinition {
  habitKey: string;
  name: string;
  domain: HabitDomain;
  suggestedLabel: string;
  defaultFrequency: HabitFrequency;
  defaultTarget?: HabitTarget | null;
  timeOfDay?: "Morning" | "Afternoon" | "Evening" | "Anytime";
  description?: string;
}

export const MASTER_HABIT_CATALOG: Record<string, MasterHabitDefinition> = {
  "sunlight-exposure": {
    habitKey: "sunlight-exposure",
    name: "Sunlight Outdoor Exposure",
    domain: "Sleep",
    suggestedLabel: "Health",
    defaultFrequency: { type: "daily" },
    defaultTarget: { type: "time", goal: 10, unit: "mins" },
    timeOfDay: "Morning",
    description: "Get direct outdoor sunlight within 30–60 minutes of waking.",
  },
  "hydrate-electrolytes": {
    habitKey: "hydrate-electrolytes",
    name: "Hydrate + Electrolytes",
    domain: "Hydration",
    suggestedLabel: "Health",
    defaultFrequency: { type: "daily" },
    defaultTarget: { type: "count", goal: 500, unit: "ml" },
    timeOfDay: "Morning",
    description: "Rehydrate with water and a pinch of unrefined salt before coffee.",
  },
  "cold-shower-reset": {
    habitKey: "cold-shower-reset",
    name: "Cold Shower Reset",
    domain: "Recovery",
    suggestedLabel: "Health",
    defaultFrequency: { type: "daily" },
    defaultTarget: { type: "time", goal: 2, unit: "mins" },
    timeOfDay: "Morning",
    description: "End shower with 2 minutes of cold water for a dopamine boost.",
  },
  "delay-caffeine": {
    habitKey: "delay-caffeine",
    name: "Delay Caffeine 90 Mins",
    domain: "Nutrition",
    suggestedLabel: "Health",
    defaultFrequency: { type: "weekdays" },
    timeOfDay: "Morning",
    description: "Wait 90–120 minutes post-waking before consuming your first coffee.",
  },
  "uninterrupted-focus-block": {
    habitKey: "uninterrupted-focus-block",
    name: "Uninterrupted Focus Block",
    domain: "Productivity",
    suggestedLabel: "Work",
    defaultFrequency: { type: "weekdays" },
    defaultTarget: { type: "time", goal: 90, unit: "mins" },
    timeOfDay: "Morning",
    description: "Single-task on priority #1 with zero notifications or open tabs.",
  },
  "zero-phone-first-hour": {
    habitKey: "zero-phone-first-hour",
    name: "Zero Phone First Hour",
    domain: "Digital Minimalism",
    suggestedLabel: "Mindset",
    defaultFrequency: { type: "daily" },
    timeOfDay: "Morning",
    description: "Do not open email or social media during your first waking hour.",
  },
  "evening-daily-shutdown": {
    habitKey: "evening-daily-shutdown",
    name: "Evening Daily Shutdown",
    domain: "Productivity",
    suggestedLabel: "Work",
    defaultFrequency: { type: "weekdays" },
    timeOfDay: "Evening",
    description: "Review open tasks, plan tomorrow's top priority, and close all work tabs.",
  },
  "daily-movement-workout": {
    habitKey: "daily-movement-workout",
    name: "Daily Movement / Workout",
    domain: "Strength",
    suggestedLabel: "Fitness",
    defaultFrequency: { type: "daily" },
    defaultTarget: { type: "time", goal: 30, unit: "mins" },
    timeOfDay: "Anytime",
    description: "Resistance training, run, or brisk exercise session.",
  },
  "daily-step-goal": {
    habitKey: "daily-step-goal",
    name: "Daily Step Goal",
    domain: "Cardio",
    suggestedLabel: "Fitness",
    defaultFrequency: { type: "daily" },
    defaultTarget: { type: "count", goal: 8000, unit: "steps" },
    timeOfDay: "Anytime",
    description: "Maintain active non-exercise activity thermogenesis (NEAT).",
  },
  "post-workout-mobility": {
    habitKey: "post-workout-mobility",
    name: "Post-Workout Mobility",
    domain: "Mobility",
    suggestedLabel: "Health",
    defaultFrequency: { type: "daily" },
    defaultTarget: { type: "time", goal: 10, unit: "mins" },
    timeOfDay: "Evening",
    description: "Stretching and foam rolling for muscle recovery.",
  },
  "code-side-project": {
    habitKey: "code-side-project",
    name: "Code Side Project / OSS",
    domain: "Learning",
    suggestedLabel: "Learning",
    defaultFrequency: { type: "timesPerWeek", times: 4 },
    defaultTarget: { type: "time", goal: 45, unit: "mins" },
    timeOfDay: "Evening",
    description: "Build personal projects or contribute to open-source repos.",
  },
  "read-engineering-docs": {
    habitKey: "read-engineering-docs",
    name: "Read Engineering Docs/Articles",
    domain: "Learning",
    suggestedLabel: "Learning",
    defaultFrequency: { type: "weekdays" },
    defaultTarget: { type: "time", goal: 15, unit: "mins" },
    timeOfDay: "Afternoon",
    description: "Stay current on architecture patterns, blog posts, or RFCs.",
  },
  "ergonomic-stretch-walk": {
    habitKey: "ergonomic-stretch-walk",
    name: "Ergonomic Stretch & Walk",
    domain: "Preventive",
    suggestedLabel: "Health",
    defaultFrequency: { type: "weekdays" },
    defaultTarget: { type: "count", goal: 3, unit: "breaks" },
    timeOfDay: "Anytime",
    description: "Stand up, stretch wrists and posture every 90 minutes.",
  },
  "log-daily-expenses": {
    habitKey: "log-daily-expenses",
    name: "Log Daily Expenses",
    domain: "Finance",
    suggestedLabel: "Finance",
    defaultFrequency: { type: "daily" },
    timeOfDay: "Evening",
    description: "Record all transactions for complete financial visibility.",
  },
  "zero-impulse-buy": {
    habitKey: "zero-impulse-buy",
    name: "Zero Impulse Buy Challenge",
    domain: "Finance",
    suggestedLabel: "Finance",
    defaultFrequency: { type: "daily" },
    timeOfDay: "Anytime",
    description: "Enforce a 48-hour cooling period for non-essential purchases.",
  },
  "weekly-budget-audit": {
    habitKey: "weekly-budget-audit",
    name: "Weekly Net Worth & Budget Audit",
    domain: "Finance",
    suggestedLabel: "Finance",
    defaultFrequency: { type: "custom", days: [0] },
    defaultTarget: { type: "time", goal: 15, unit: "mins" },
    timeOfDay: "Morning",
    description: "Review savings targets, subscriptions, and portfolio growth.",
  },
  "nightly-stoic-journal": {
    habitKey: "nightly-stoic-journal",
    name: "Nightly Stoic Journal",
    domain: "Sleep",
    suggestedLabel: "Personal",
    defaultFrequency: { type: "daily" },
    defaultTarget: { type: "time", goal: 10, unit: "mins" },
    timeOfDay: "Evening",
    description: "Answer: What went well? What could I have done better?",
  },
  "screen-free-before-sleep": {
    habitKey: "screen-free-before-sleep",
    name: "Screen-Free 60 Mins Before Sleep",
    domain: "Digital Minimalism",
    suggestedLabel: "Health",
    defaultFrequency: { type: "daily" },
    timeOfDay: "Evening",
    description: "Turn off phone/laptop screens to allow natural melatonin production.",
  },
  "prepare-environment-tomorrow": {
    habitKey: "prepare-environment-tomorrow",
    name: "Prepare Environment for Tomorrow",
    domain: "Productivity",
    suggestedLabel: "Personal",
    defaultFrequency: { type: "daily" },
    timeOfDay: "Evening",
    description: "Tidy your space, prep tomorrow's items, and make your bed.",
  },
};
